---

- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}_{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution|lower }}.yaml"
    - "{{ ansible_os_family|lower }}_{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_os_family|lower }}.yaml"

- name: Ensure requirements are present.
  package:
    name: "{{ syncthing__requirements }}"
    state: present

- name: Ensure Syncthing group is Present.
  group:
    name: "{{ syncthing__group }}"
    state: present

- name: Ensure Syncthing user is Present.
  user:
    name: "{{ syncthing__owner }}"
    home: "{{ syncthing__home }}"
    group: "{{ syncthing__group }}"
    shell: "/usr/sbin/nologin"
    state: present

- name: Ensure Syncthing is Present.
  unarchive:
    src: "{{ syncthing__upstream_url[ansible_architecture] }}"
    dest: "{{ syncthing__install_dir }}/"
    owner: "{{ syncthing__owner }}"
    group: "{{ syncthing__group }}"
    keep_newer: yes
    remote_src: yes
    extra_opts:
      - "--strip=1"
      - "--wildcards"
      - "*/syncthing"

- name: Ensure Syncthing Service is Present.
  template:
    src: "syncthing.rc-d.j2"
    dest: "{{ syncthing__service_dir }}/syncthing"
    owner: "{{ syncthing__owner }}"
    group: "{{ syncthing__group }}"
    mode: "u=rwx,g=rx,o=xr"

- name: Ensure Syncthing Service is Enabled and Started
  service:
    name: "{{ syncthing__service }}"
    enabled: yes
    state: started
